name:            "Hugo Build Project"
author:          Benjamin Becker
description:     "Perform a hugo build"
branding:
  icon:          arrow-right
  color:         purple

runs:
  using:         'docker'
  image:         'docker://blbecker/hugo-build:0.111.3'

inputs:
  hugo_args:
    description: "Additional arguments to pass to hugo"
    required:    false
